aeropuerto-proyect/aeropuerto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('vuelos.urls')),
    path('',include('clientes.urls')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root = settings.MEDIA_ROOT)

aeropuerto-proyect/clientes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = 'clientes'
urlpatterns = [
    path('login', views.login, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('signup', views.registrar_usuario, name='signup'),
    path('perfil', views.perfil, name='perfil'),
    path('reserva-<str:vuelo>', views.reserva, name='reserva'),
    path('usuarioAdmin/', views.usuarios_admin, name='usuarios_admin'),
    path('clienteAdmin-<int:cliente_id>/', views.cliente_perfil_admin, name='clientePerfilAdmin'),
    path('eliminarCliente-<int:cliente_id>/', views.eliminar_cliente, name='eliminarCliente'),
    path('cancelar-reserva-<int:id>', views.cancelar_reserva, name='cancelar_reserva'),
    path('editar-perfil', views.editar_perfil, name='editar_perfil'),
]

aeropuerto-proyect/vuelos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views
app_name = 'vuelos'
urlpatterns = [
    path('', views.index, name='index'),
    path('vuelo/', views.vuelo, name='vuelo'),
    path('registrar-aerolinea/', views.registrar_aerolinea, name='registrar-aerolinea'),
    path('registrar-vuelo/', views.registrar_vuelo, name='registrar-vuelo'),
    path('registrar-escala-<str:id>', views.registrar_escala, name='registrar-escala'),
    path('modificar-aerolinea-<int:id>', views.modificar_aerolinea, name='modificar-aero'),
    path('vuelo-<str:id>', views.vista_vuelo, name='vista-vuelo'),
    path('admin-vuelo-<str:id>', views.vuelo_admin, name='vuelo-admin'),
    path('eliminar-vuelo-<str:id>', views.eliminar_vuelo, name='eliminar-vuelo'),
    path('editar-vuelo-<str:id>', views.editar_vuelo, name='editar-vuelo'),
    path('aerolineas/', views.aerolineas, name='aerolineas'),
    path('eliminar-aerolinea-<int:id>', views.eliminar_aerolinea, name='eliminar-aerolinea'),
    path('registrar-ciudad', views.registrar_ciudad, name='registrar-ciudad'),
    path('modificar-ciudad-<int:id>', views.modificar_ciudad, name='modificar-ciudad'),
    path('ciudades/', views.ciudades, name='ciudades'),
    path('clima-<int:postal>/', views.clima, name='clima'),

]

aeropuerto-proyect/vuelos/models.py
from django.db import models
from django.contrib.auth.models import User

# MODELOS

class Aerolinea(models.Model):
    nombre = models.CharField(max_length=100,verbose_name="nombre")
    
    def __str__(self):
        return self.nombre


class Ciudades(models.Model):
    postal = models.IntegerField(primary_key=True)
    nombre = models.CharField(max_length = 30,null=False)
    foto = models.ImageField(upload_to='vuelos/ciudades/',null = True, blank = True)

    def __str__(self):
        return self.nombre

class Vuelo(models.Model):
    id_vuelo = models.CharField(max_length=30,primary_key=True, verbose_name="id_vuelo")
    aerolinea = models.ForeignKey(Aerolinea,on_delete=models.CASCADE, verbose_name="aerolinea")
    destino = models.ForeignKey(Ciudades,on_delete=models.CASCADE)
    costo = models.FloatField(blank=False,null=False, verbose_name="costo")
    fecha = models.DateTimeField(blank=False,null=False)
    requisitos = models.TextField(null=False,blank=False)
    def __str__(self):
        return str(self.id_vuelo)


class Escala(models.Model):
    vuelo = models.ForeignKey(Vuelo,on_delete=models.CASCADE)
    ciudad_escala = models.ForeignKey(Ciudades,on_delete=models.CASCADE)
    fecha_escala = models.DateTimeField(null=False,blank=False)

    def __str__(self):
        return f'{self.vuelo},{self.ciudad_escala}' 

aeropuerto-proyect/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError 

from vuelos.models import Aerolinea, Ciudades


# -*- coding:utf-8 -*-
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext as _

class Loginform(forms.Form):
    usuario = forms.CharField(max_length=20,label='Nombre de usuario')
    contrasena = forms.CharField(widget=forms.PasswordInput(),
            label='Contraseña')


class RegistroClienteform(forms.Form):
    # CSS ERRORS
    error_css_class = 'invalid-feedback'
    required_css_class = 'required'
    error_css_class = "error"
 
    # COMPONENETES 
    cc = forms.IntegerField(required=True,label='Identificacion',help_text="Debe contener al menos 7 digitos" )
    nombre = forms.CharField(max_length=20,required=True, label='Nombre')
    apellido = forms.CharField(max_length=20,required=True, label='Apellido')
    username = forms.CharField(max_length=20,required=True )
    email = forms.EmailField(max_length=30,required=True ,label='Email')
    password1 = forms.CharField(widget=forms.PasswordInput(),label="Contraseña", help_text="Debe contener al menos 8 caracteres, un caracter especial y una mayuscula")
    password2 = forms.CharField(widget=forms.PasswordInput(),label="Confirmar Contraseña", help_text ="La contraseña de nuevo")

    # CAMBIOS EN EL CSS
    cc.widget.attrs.update({'class': 'form-control'})  
    nombre.widget.attrs.update({'class': 'form-control'})  
    apellido.widget.attrs.update({'class': 'form-control'})  
    username.widget.attrs.update({'class': 'form-control'}) 
    email.widget.attrs.update({'class': 'form-control'}) 
    password1.widget.attrs.update({'class': 'form-control'})  
    password2.widget.attrs.update({'class': 'form-control'})  

    def clean_password2(self):
        psswrd1 = self.cleaned_data.get("password1")
        psswrd2 = self.cleaned_data.get("password2")
        
        if not(psswrd1 and psswrd2):
            raise ValidationError("Los campos son obligatorios")
        elif psswrd1 != psswrd2:
            raise ValidationError("Las contraseñas no coinciden")
        elif len(psswrd1) < 8:
            raise ValidationError("La contraseñas debe tener almenos 8 caracteres")
        elif len(psswrd1) > 20:
            raise ValidationError("La contraseñas debe tener maximo 20 caracteres")
        elif psswrd1.isalpha():
            raise ValidationError("La contraseñas debe tener al menos un caracter especial")
        elif psswrd1.lower() == psswrd1:
            raise ValidationError("La contraseña debe tener al menos una mayuscula")
        return psswrd2

    def clean_cc(self):
        cc = self.cleaned_data.get("cc")
        if len(str(cc)) < 7:
            raise ValidationError("La Identificacion no es valida")
        return cc

    def clean_username(self):
        newusername = self.cleaned_data.get("username")
        number_usrs = User.objects.filter(username=newusername).count()
        if number_usrs > 0:
            raise ValidationError("Este nombre de usuario ya se encuentra en uso",'error_user')
        return newusername

    def as_div(self):
        output = []
        
        for boundfield in self: #see original Form class __iter__ method
            row_template = u'''
            <div class=" mb-3 %(div_class)s">
                %(label)s
                <div class="input %(input_class)s">
                    %(field)s
                    <span class="help-block">%(help_text)s </span>
                </div>
                <div class="invalid-feedback">%(error_l)s </div>
            </div>
            '''
            row_dict = {
                "input_class" : "",
                "div_class" : "",
                "required_label" : "",
                "field" : boundfield.as_widget(),
                "label" : boundfield.label_tag(),
                "help_text" : boundfield.help_text,
                "error_l" : "",
            }

            
            if boundfield.errors:
                row_dict["error_l"]  = '''<div class="alert alert-danger" role="alert">''' + str(boundfield.errors )+ '''
                                        </div>'''

            output.append(row_template % row_dict)
        return mark_safe(u'\n'.join(output))

"""
    def clean(self):
        cd = self.cleaned_data
        # {'cc': 12345, 'username': 'asdf', 'email': 'qefasdf@gmail.com', 'password1': '1234', 'password2': '12346'}
        psswrd1 = cd.get("password1")
        psswrd2 = cd.get("password2")
        new_username = cd.get("username")
        cc = cd.get("cc")
        number_usrs = User.objects.filter(username=new_username)
        
        print("VALIDATION OF DATA-----------_>",cd)
        if psswrd1 != psswrd2:
            raise ValidationError("Las contraseñas no coinciden")
        elif len(psswrd1) < 8:
            raise ValidationError("La contraseñas debe tener almenos 8 caracteres")
        elif len(psswrd1) > 20:
            raise ValidationError("La contraseñas debe tener maximo 20 caracteres")
        elif psswrd1.isalpha():
            raise ValidationError("La contraseñas debe tener al menos un caracter especial")
        elif psswrd1.lower() == psswrd1:
            raise ValidationError("La contraseña debe tneer al menos una mayuscula")
        elif len(cc) < 8:
            raise ValidationError("La Identificacion no es valida")
        elif number_usrs > 0:
            raise ValidationError("Este nombre de usuario ya se encuentra en uso")
        
        return cd
"""
"""
    password1 = forms.CharField(widget=forms.PasswordInput(),label="Contraseña")
    password2 = forms.CharField(widget=forms.PasswordInput(),label="Confirmar Contraseña")
    
    def clean(self):
        cd = self.get.cleaned_data

        psswrd1 = cd.get("password1")
        psswrd2 = cd.get("password2")
        #username = cd.get("username")
        cc = cd.get("cc")
        number_same_users = User.objects.filter(username=cd.get('username')).count()

        if  psswrd1 != psswrd2:
            raise ValidationError("Las claves no coinciden")
        elif int(cc) < 0 or len(cc) < 8:
            raise ValidationError("La identificacion debe tener almenos 8 digitos")
        elif number_same_users > 0: 
            raise ValidationError("Ya existen ese nombre de usuario")
        
        return cd
        
"""

class Aerolineaform(forms.Form):
    aerolinea = forms.CharField(max_length=20, label='Nombre aerolinea')
 

class Vueloform(forms.Form):
    id_vuelo = forms.CharField(max_length=30, label='Codigo del vuelo')
    id_aerolinea = forms.ModelChoiceField(Aerolinea.objects.all())
    destino = forms.ModelChoiceField(Ciudades.objects.all())
    costo = forms.FloatField(label='Precio')
    fecha_vuelo = forms.DateField(label='Fecha de vuelo')
    requisitos = forms.CharField(widget=forms.Textarea, label='Requisitos')
    

class Escalaform(forms.Form):
#    id_vuelo = forms.CharField(max_length=30, label='Codigo del vuelo',)
    procedencia = forms.ModelChoiceField(Ciudades.objects.all())
    fecha_llegada = forms.DateField(label='Fecha de llegada', )


class CiudadForm(forms.Form):
    postal = forms.IntegerField(label = 'Codigo postal')
    nombre = forms.CharField(max_length=30,label='Nombre de la ciudad')
    foto = forms.ImageField(label='Foto de la ciudad')

class editar_perfilForm(forms.Form):
    nombre = forms.CharField(max_length=30,label='Nombre')
    apellido = forms.CharField(max_length=30,label='Apellido')
    email = forms.EmailField(label='Email')
    foto = forms.ImageField(label='Foto de perfil')

aeropuerto-proyect/vuelos/templates/vuelos/aerolineas.html
{% extends 'vuelos/base.html' %}

{% load static %}
{% block content %}
<title> Aerolineas </title>
<br>
<div class="container mt-5 mb-5" >
  <div class="row d-flex align-items-center justify-content-center">
    <div class="col-md-6" >
        <div class="card px-5 py-5">
          <div class="form-input"><br>
            <h1> Aerolineas Registradas:</h1>
            <br>
            <ul>
	      {% for aerolinea in aerolineas %}
	      <li> <a href="{% url 'vuelos:modificar-aero' aerolinea.id%}">{{aerolinea.nombre}}</a></li>
              {% endfor %}
                
            </ul>
            <br><br>
            <a href="{% url 'vuelos:registrar-aerolinea' %}">
                <button type='submit' class="btn-success btn btn-primary mr-4 signup">Registrar aerolinea</button>
            </a>
                                      


          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
{% endblock %}

aeropuerto-proyect/vuelos/templates/vuelos/clima.html
{% extends 'vuelos/base.html' %} {% load static %} {% block content %}
<title>Clima</title>
<br />
<div class="container mt-5 mb-5">
  <div class="row d-flex align-items-center justify-content-center">
    <div class="col-md-12">
      <div class="card">
        
        <label class="form-check-label">Ciudad: <p>{{ciudad}}</p> </label><br>
        <label class="form-check-label">Descripción: <p>{{descripcion}}</p> </label><br>
        <label class="form-check-label">Temperatura actual: <p>{{tempertura}} °C </p></label><br>
        <label class="form-check-label">Temperatura máxima: <p>{{tempertura_max}} °C </p></label><br>
        <label class="form-check-label">Temperatura mínima: <p>{{tempertura_min}} °C </p></label><br>
        <label class="form-check-label">Presión: <p>{{presion}}  hPa </p></label><br>
        <label class="form-check-label">Humedad: <p>{{humedad}} g/m3</p></label><br>
        <label class="form-check-label">Velocidad del viento: <p>{{viento_velocidad}}  m/s </p></label><br>
        <label class="form-check-label">Orientación del viento: <p>{{viento_deg}} ° </p></label><br>
        
        
        
        
        
        
        
        
      
      </div>
    </div>
  </div>
</div>
<br />

<script>
{
    "coord":
    {
        "lon":-76.2978,
        "lat":3.9009
    },
    "weather":
    [{
        "id":802,
        "main":"Clouds",
        "description":"nubes dispersas",
        "icon":"03n"
    }],
    "base":"stations",
    "main":
    {
        "temp":19.4,
        "feels_like":19.56,
        "temp_min":17.78,
        "temp_max":21,
        "pressure":1013,
        "humidity":83
    },
    "visibility":10000,
    "wind":
    {
        "speed":2.06,
        "deg":60
    },
    "clouds":
    {
        "all":40
    },
    "dt":1618200181,
    "sys":
    {
        "type":1,
        "id":8590,
        "country":"CO",
        "sunrise":1618138814,
        "sunset":1618182697
    },
    "timezone":-18000,
    "id":0,
    "name":"Guadalajara De Buga",
    "cod":200
}
</script>

{% endblock %}

aeropuerto-proyect/vuelos/templates/vuelos/eliminarVuelo.html
{% extends 'vuelos/base.html' %}

<title>Eliminar Vuelo</title>
{% block content %}
    <br>
    <div class='text-center ' id='uwu'><br>
      <h1>¿Seguro que desea eliminar este vuelo?</h1><br>
      <form method="POST" enctype='multipart/form-data'>
          {% csrf_token %}<br>
          <button type="submit" class="btn-danger btn btn-primary mr-4 signup" > Eliminar</button>
      </form>
      <br>
      <a href="javascript: history.go(-1)">  
        <button class="btn-primary btn btn-primary mr-4 cancel"> Cancelar</button>
      </a>
    </div><br>
    {% endblock %}

aeropuerto-proyect/vuelos/templates/vuelos/login.html
{% extends 'vuelos/base.html' %}

{% load static %}
{% block content %}
{% if messages %}
    {% for message in messages %}
      <script>alert("{{message|safe}}")</script>
    {% endfor %}
{% endif %}<title> Iniciar Sesion </title>
<br>
<div class="container mt-5 mb-5" >
  <div class="row d-flex align-items-center justify-content-center">
    <div class="col-md-6" >
        <div class="card px-5 py-5">
          <div class="form-input">
            <form method="post">
              {% csrf_token %}
              <label for="id_usuario" class="form-check-label"> Nombre de usuario: </label>
              <input type="text" name="usuario" maxlength="20" required="" id="id_usuario" class="form-control">

              <br>
              <label for="id_contrasena" class="form-check-label">Contraseña:</label>
              <input type="password" name="contrasena" required="" id="id_contrasena" class="form-control">

              <br>
              <button class="btn btn-primary mr-4 signup" type="submit">Iniciar Sesión</button>
            </form>
            {% if error != None %}
            <br>
            <h1>{{error}}</h1>
            {% endif %}
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
{% endblock %}

aeropuerto-proyect/vuelos/templates/vuelos/perfil.html
{% extends 'vuelos/base.html' %} {% load static %}
<title>Mi perfil</title>
{% block content %}
<div class="profile-box banner-p">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="profile-b">
          <img src="{% static 'vuelos/images/lag-63.png' %}" alt="#" />
        </div>
      </div>
    </div>
  </div>
</div>
<div class="product-profile-box">
  <div class="container">
    <div class="row">
      <div class="col-md-2 col-sm-4 pr">
        <div class="profile-pro-left">
          <div class="left-profile-box-m">
            <div class="pro-img">
              <img src="{{usuario.image_perfil.url }}" alt="#" />
            </div>
            <div class="pof-text">
              <h3>
                {{usuario.usuario_dj.first_name}}
                {{usuario.usuario_dj.last_name}}

                <div class="check-box"></div>
              </h3>
            </div>
            <br />
            <br />
            <br />
            <span> CC:{{usuario.cc}}</span>
            <br />
            <span>Username:{{usuario.usuario_dj.username}} </span>
            <br />
            <span>Email:{{usuario.usuario_dj.email}}</span>
            <br />
          </div>
        </div>
      </div>
      <div class="col-md-10 col-sm-8">
        <div class="profile-pro-right">
          <div class="panel with-nav-tabs panel-default">
            <div class="panel-heading clearfix">
              <ul class="nav nav-tabs pull-left">
                <li class="active">
                  <a data-toggle="tab"
                    >Reservas disponibles:
                    <span>{{usuario.vuelos_disponibles}}</span></a
                  >
                </li>
              </ul>
              <ul class="nav nav-tabs pull-right">
                <li>
                  <a href="{% url 'clientes:editar_perfil' %}">
                    <span> Editar perfil </span></a
                  >
                </li>
              </ul>
            </div>
            <div class="panel-body">
              <div class="tab-content">
                <div class="tab-pane fade in active" id="tab1default">
                  <div class="product-box-main row">
                    {%for reserva in reservas%}
                    <div class="col-md-4 col-sm-6">
                      <div class="small-box-c">
                        <div class="small-img-b">
                          <img
                            src="{{ reserva.vuelo.destino.foto.url }}"
                            alt="#"
                          />
                        </div>
                        <div class="dit-t clearfix">
                          <div class="left-ti">
                            <h4>{{ reserva.vuelo.destino.nombre }}</h4>
                            <p>{{ reserva.vuelo.fecha}}</p>
                          </div>
                          <a href="#" tabindex="0">{{ reserva.vuelo.costo}}</a>
                        </div>
                        <div class="prod-btn">
                           <a href="{% url 'clientes:cancelar_reserva' reserva.id%}"><i class="fa fa-star" aria-hidden="true"></i>
                            Cancelar
                           </a>
                           {% if dia_actual == reserva.vuelo.fecha.day  %}
                              <a href="{% url 'vuelos:clima' reserva.vuelo.destino.postal %}">
                              Clima
                              </a>
                           {% endif %}
                        </div>
                      </div>
                    </div>
                    {%endfor%}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

aeropuerto-proyect/vuelos/templates/vuelos/registroVuelo.html
{% extends 'vuelos/base.html' %}
{% block content %}
<title>Registrar vuelo</title>
<br>

<div class="container mt-5 mb-5" >
  <div class="row d-flex align-items-center justify-content-center">
    <div class="col-md-6" >
        <div class="card px-5 py-5">
          <div class='text-left'>
            <br>
            <h1> Registrar vuelo</h1>
            <br>
            <form method='POST'>
              {% csrf_token %}
              <br>
              <label for="id_id_vuelo" class="form-check-label"> Código de vuelo: </label><br>
              <input type="text" name="id_vuelo" maxlength="30" required="" id="id_id_vuelo" class="form-control">
	            <br>
              <label for="id_id_aerolinea" class="form-check-label"> Aerolinea: </label><br>
                
              <!-- <select class="form-control select2"> -->
              <!--   <option value="" selected="">---------</option> -->
              <!-- </select> -->
	
	            {{form.id_aerolinea}}
	            <br><br>

              <label for="id_destino" class="form-check-label"> Destino: </label><br>
	      {{form.destino}} 
	            <br>
              <label for="id_costo" class="form-check-label"> Precio: </label>
              <br>
              <input type="number" name="costo" step="any" required="" id="id_costo" class="form-control"> 
              <!-- <input type="text" name="id_costo" maxlength="30" required="" id="id_costo" class="form-control"> -->
	      <br>
	      <label for='id_fecha_vuelo' class="form-check-label"> Día del vuelo: </label><br>
	      <select id='id_fecha_vuelo' name='fecha_vuelo' class="form-check-label">
          {%for dia in dias%}
          <option value={{dia}}>{{dia}}</option>
          {%endfor%}
	      </select>
        <br><br>
	      <label for='id_hora_vuelo' class="form-check-label"> Hora del vuelo: (Ejemplo: 23:59) </label>

	      <input type='text' name="hora_vuelo" step="any" required="" id="id_hora_vuelo" class="form-control" placeholder="HH:MM"> 
	<br>

	      <label for='id_requisitos' class="form-check-label"> Requisitos:  </label>
              <textarea name="requisitos" cols="40" rows="10" required="" id="id_requisitos" class="form-control"></textarea>
	            <br><br>
              <button type='submit' class='btn-success btn btn-primary mr-4 signup'>Registrar</button>
            </form>
          </div>
          <br>
        </div>
      </div>
    </div>
  </div>
</div>
<br>






{% endblock %}

aeropuerto-proyect/vuelos/templates/vuelos/signup.html
{% extends 'vuelos/base.html' %}

{% load static %}
{% block content %}
<title> Iniciar Sesion </title>
<br>
<div class="container mt-5 mb-5" >
  <div class="row d-flex align-items-center justify-content-center">
    <div class="col-md-6" >
        <div class="card px-5 py-5">
          <div class="form-input"><br>
            <h1> ¡Regístrate!</h1>
            <br>
            <form method="post">
              {% csrf_token %}
              <div class="form-row">
                {{form.as_div}}
              </div>

              <!--
              <label for="id_cc">Identificacion:</label><input type="number" name="cc" required="" id="id_cc">
              <br>
              <label for="id_username" class="form-check-label">Username:</label>
              <input type="text" name="username" maxlength="20" required="" id="id_username" class="form-control">
              <br>
              <label for="id_email" class="form-check-label">Email:</label>
              <input type="email" name="email" maxlength="30" required="" id="id_email" class="form-control">
              <br>
              <label for="id_password1" class="form-check-label">Contraseña:</label>
              <input type="password" name="password1" required="" id="id_password1" class="form-control">
              <br>
              <label for="id_password2">Confirmar Contraseña:</label><input type="password" name="password2" required="" id="id_password2">
              -->
              <br>
              <button class="btn-success btn btn-primary mr-4 signup" type="submit"> Registrarse </button>
            </form>
            {% if error != None %}
          <script>
            alert('{{error}}')
          </script>
            {% endif %}
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
{% endblock %}

aeropuerto-proyect/vuelos/templates/vuelos/usuariosAdmin.html
{% extends 'vuelos/base.html' %}

{% load static %}
{% block content %}
<title> Usuairos - administracion </title>
<br>
<div class="container mt-5 mb-5" >
    <div class="row d-flex align-items-center justify-content-center">
        <div class="col-md-12" >
            <div class="card">
                <div class="card-header">
                    <h2>CLIENTES<h2>
                </div>
                <br>
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Identificación</th>
                                <th scope="col">Nombre </th>
                                <th scope="col">Apellido</th>
                                <th scope="col">Username</th>
                                <th scope="col">Correo</th>
                            </tr>
                        </thead>
                        {% for client in clientes %}
                            <tr>
                                <th>
                                    <a href="{% url 'clientes:clientePerfilAdmin' client.cc %}" > {{client.cc}} </a>
                                </th>
                                <td>{{client.usuario_dj.first_name}}</td>
                                <td>{{client.usuario_dj.last_name}}</td>
                                <td>{{client.usuario_dj.username}}</td>
                                <td>{{client.usuario_dj.email}}</td>
                                <td>
                                    <a href="{% url 'clientes:eliminarCliente' client.cc %}">
                                        <button type="button" class="btn-danger btn">
                                            Eliminar
                                        </button>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
                
            </div>
        </div>
      
    </div>
  
</div>
<br>
{% endblock %}

aeropuerto-proyect/vuelos/templates/vuelos/vuelo_admin.html
{% extends 'vuelos/base.html' %}

{% load static %}
{% block content %}
      
<title> Vuelo admin </title>
      <!-- Modal -->
      <div class="product-page-main">
         <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <div class="prod-page-title">
                     <h2>Vuelo a {{vuelo.destino}}</h2>
                     <p>Numero de vuelo  <b> {{vuelo.id_vuelo}},{{vuelo.aerolinea}} </b> </p>
                  </div>
               </div>
            </div>
            <div class="row">
               
               <div class="col-md-7 col-sm-8">
                  <div class="md-prod-page"> 
                     <div class="md-prod-page-in">
                        <div class="page-preview">
                           <div class="preview">
                              <div class="preview-pic tab-content">
                                 <div class="tab-pane active" id="pi-1"><img src="{{ vuelo.destino.foto.url }}" alt="#" /></div>
                              </div>
                           </div>
                        </div>
                        
                     </div>
                     <div class="description-box">
                        <div class="dex-a">
                           <h4>Descripción</h4>
			   <p>               {{vuelo.requisitos}}            </p>
                           <br>
                           <h4>Escalas</h4>
			  {% for escala in escalas %}
                           <p>-{{escala.ciudad_escala}}</p>
			  {% endfor %}
                        </div>
                        <div class="spe-a">
                           <h4>Especificaciones</h4>
                           <ul>
                              <li class="clearfix">
                                 <div class="col-md-4">
                                    <h5>Pasajeros</h5>
                                 </div>
                                 <div class="col-md-8">
                                    <p>1</p>
                                 </div>
                              </li>
                              <li class="clearfix">
                                 <div class="col-md-4">
                                    <h5>Maletas</h5>
                                 </div>
                                 <div class="col-md-8">
                                    <p>1</p>
                                 </div>
                              </li>
                              <li class="clearfix">
                                 <div class="col-md-4">
                                    <h5>Mascotas</h5>
                                 </div>
                                 <div class="col-md-8">
                                    <p>No</p>
                                 </div>
                              </li>
                              <li class="clearfix">
                                 <div class="col-md-4">
                                    <h5>Tipo de asiento</h5>
                                 </div>
                                 <div class="col-md-8">
                                    <p>Turista</p>
                                 </div>
                              </li>
                              
                           </ul>
                        </div>
                     </div>
                  </div>
                  
               </div>
               <div class="col-md-3 col-sm-12">
                  <div class="price-box-right">
                     <h4>Precio</h4>
		               <h3>${{vuelo.costo}} <span> pesos </span></h3>
                     <p>Fecha de vuelo</p>
                     <p>{{vuelo.fecha}}</p> 
                     <a href="{% url 'vuelos:editar-vuelo' vuelo.id_vuelo %}">Modificar</a>
                     <a href="{% url 'vuelos:eliminar-vuelo' vuelo.id_vuelo%}">Eliminar</a>
                     <h5>
                        <i class="fa fa-clock-o" aria-hidden="true"></i> <strong>2 horas</strong> en vuelo.</h5>
                  </div>
               </div>
            </div>
         </div>
      </div>

      {% endblock %}
      